export const progressPlanConstants = {

    RESIZE: 'RESIZE',
    COLOR: "COLOR",
    DATE: "DATE",
    REF_CONTAINER: "REF_CONTAINER",
    RESIZE_DATE: "RESIZE_DATE",

    ADD_PROGRESS_PLAN: 'ADD_PROGRESS_PLAN',
    PROGRESS_PLAN_DATA: "PROGRESS_PLAN_DATA"
};
