export const progressPlanConstants = {

    RESIZE: 'RESIZE',
    COLOR: "COLOR",

    REF_CONTAINER: "REF_CONTAINER",
    COLOR_REF: "COLOR_REF",
    TITLE_REF: "TITLE_REF",
    EMPLOYEE_REF: "EMPLOYEE_REF",
    INFO_REF:"INFO_REF",

    DATE: "DATE",
    RESIZE_DATE: "RESIZE_DATE",
    DRAGGABLE_DATA: "DRAGGABLE_DATA",

    PROGRESS_PLAN_DATA: "PROGRESS_PLAN_DATA",

    ADD_MONTH: "ADD_MONTH",
    MINUS_MONTH: "MINUS_MONTH",

    EVENT_ID: "EVENT_ID",

    DELETE_PROGRESS: "DELETE_PROGRESS"
};
