export const projectConstants = {

    PROJECT_DATA: "PROJECT_DATA",
    PROJECT_UPDATE: "PROJECT_UPDATE",
    PROJECT_DATA_ERROR: "PROJECT_DATA_ERROR",

    EDIT_MODUS: "EDIT_MODUS",
    UPDATE_PROJECT_TABLE: "UPDATE_PROJECT_TABLE",
    PROJECT_TABLE_ONCHANGE: "PROJECT_TABLE_ONCHANGE",

    ADD_PROJECT: "ADD_PROJECT",

    DELETE_PROJECT_ID: "DELETE_PROJECT_ID",
    PROJECT_REMOVED: "PROJECT_REMOVED"
};