export const projectConstants = {

    PROJECT_DATA: "PROJECT_DATA",
    PROJECT_UPDATE:"PROJECT_UPDATE",
    PROJECT_DATA_ERROR: "PROJECT_DATA_ERROR",

    EDIT_MODUS :"EDIT_MODUS",
    UPDATE_PROJECT_TABLE:"UPDATE_PROJECT_TABLE",
    DELETE_PROJECT:"DELETE_PROJECT",
    
    ADD_PROJECT:"ADD_PROJECT",
    PROJECT_ID:"PROJECT_ID"
};