export const userConstants = {

    MANAGER_DATA: "MANAGER_DATA",
    MANAGER_DATA_ERROR: "MANAGER_DATA_ERROR",

    EMPLOYEE_DATA: "EMPLOYEE_DATA",
    EMPLOYEE_DATA_ERROR: "EMPLOYEE_DATA_ERROR",

    USER_DATA_ERROR: "USER_DATA_ERROR",
    GET_FILE: "GET_FILE",

    DELETED_EMPLOYEE: "DELETED_EMPLOYEE"
};