export const userConstants = {

    MANAGER_DATA: "MANAGER_DATA",
    MANAGER_EMPLOYEE_UPDATE:"MANAGER_EMPLOYEE_UPDATE",
    MANAGER_DATA_ERROR: "MANAGER_DATA_ERROR",

    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
    GET_FILE: "GET_FILE",

    DELETED_EMPLOYEE: "DELETED_EMPLOYEE"
};